version: '3.8'
services:
 db:
   image: mariadb
   restart: unless-stopped
   networks:
     - zabbix
   environment:
     MARIADB_ROOT_PASSWORD: secreto
     MARIADB_DATABASE: zabbix
     MARIADB_USER: zabbix
     MARIADB_PASSWORD: muysecreto
   command:
     - --character-set-server=utf8
     - --collation-server=utf8_bin
     - --default-authentication-plugin=mysql_native_password
   container_name: mysql_zabbix

 java_gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.4-latest
    restart: unless-stopped
    networks:
      - zabbix
    container_name: zabbix-java-gateway
    depends_on:
      - db

 server_with_mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: muysecreto
      MYSQL_ROOT_PASSWORD: secreto
      ZBX_JAVAGATEWAY: java_gateway
    networks:
      - zabbix
    ports:
      - "10051:10051"
    container_name: zabbix-server
    depends_on:
      - db
      - java_gateway

 web_interface:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: server_with_mysql
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: muysecreto
      MYSQL_ROOT_PASSWORD: secreto
    networks:
      - zabbix
    ports:
      - "8080:8080"
    depends_on:
      - db
      - java_gateway
      - server_with_mysql

networks:
  zabbix: