version: '3.8'
services:
 db:
   image: mariadb:lts
   restart: unless-stopped
   networks:
     - zabbix
   env_file:
      - envs/db.env
   command:
     - --character-set-server=utf8
     - --collation-server=utf8_bin
     - --default-authentication-plugin=mysql_native_password
   container_name: mysql_zabbix

 server_with_mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    restart: unless-stopped
    env_file:
      - envs/server.env
    networks:
      - zabbix
    ports:
      - "10051:10051"
    container_name: zabbix-server
    depends_on:
      - db

 web_interface:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.4-latest
    restart: unless-stopped
    env_file:
      - envs/web.env
    networks:
      - zabbix
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server_with_mysql

networks:
  zabbix: